### ISSUE TITLE
Stuck on apple logo. Not being boot

### ISSUE THREAD

**Issue by evgenybozhko2** [elieserme/hackintosh#2]
Similar hardware to yours. 8700k, rx580, z370n, same wifi, ssd.
Mac os 12.3
![IMG_3110](https://user-images.githubusercontent.com/5464497/160197874-5e15a69e-55fd-4502-9b46-2a2dc038f9b7.JPG)

stuck after beginning boot. Any ideas ?

**Comment by elieserme** [comment]
Hello!

What is the BIOS version of your Gigabyte z370n?

**Comment by evgenybozhko2** [comment]
> Hello! What is the BIOS version of your Gigabyte z370n?
> […](#)

Official F14

**Comment by elieserme** [comment]
Hello again!

Did you run setup_var_3 on modified grub shell to disable CFG Lock?

**Comment by evgenybozhko2** [comment]
Does it change successfully ?
![IMG_3111](https://user-images.githubusercontent.com/5464497/160233667-2e9f556c-a08c-4285-aa08-164eab47bf5f.JPG)

How to run openCore in verbose mode?

**Comment by evgenybozhko2** [comment]
After lauch boot in berbose mode. It Being to works.

**Comment by evgenybozhko2** [comment]
Thank you. It works like a charm.
