### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by evgenybozhko2** [elieserme/hackintosh#3]
Hi, thank you for your work.
I still use the native wifi-bt card [BCM94360CS2]
In the latest implementation, it can be frozen after wakeup from sleep. So only Bluetooth turn off/on from USB mouse/keyboard can run it again. Thnak you.

**Comment by elieserme** [comment]
Hello!

For use  BCM94360CS2 you need to remove the following kexts:

AirportItlwm.kext
BlueToolFixup.kext
IntelBluetoothFirmware.kext

Enviado do meu iPhone

**Comment by evgenybozhko2** [comment]
Did it already.
![Screen Shot 2022-07-13 at 16 19 47](https://user-images.githubusercontent.com/5464497/178743392-e333823f-a448-4586-958f-30768b8fad69.png)

**Comment by elieserme** [comment]
Also, remove:

SSDT-USBW.aml from ACPI folder 

And

USBWakeFixup.kext from Kexts folder

Enviado do meu iPhone

**Comment by elieserme** [comment]
One more thing:

If you are using iMacPro1,1 SMBIOS, remove more 3 kexts:

CPUFriend.kext
CPUFriendDataProvider.kext
RestrictEvents.kext

These kexts above are only for MacPro7,1 SMBIOS.

Enviado do meu iPhone

**Comment by evgenybozhko2** [comment]
It works! Thank you.
