### ISSUE TITLE
With your latest config there a now way to enter into Modified GRUB Shel

### ISSUE THREAD

**Issue by evgenybozhko2** [elieserme/hackintosh#4]
Anyway, it's just going to start without any way to enter in open-core options. With thus terrible sound.

**Comment by elieserme** [comment]
Hello! 

It's just set in **config.plist**:

``
<key>ShowPicker</key>
<true/>
``

File is updated in last commit. Thanks to point that problem... solved now.

If you want to remove the boot chime sound set:

``
<key>PlayChime</key>
<string>Disabled</string>
``

Enjoy Sonoma!

**Comment by elieserme** [comment]
Solved.
