### ISSUE TITLE
How to revert from F14 to F12 bios?

### ISSUE THREAD

**Issue by Aazamandius** [elieserme/hackintosh#5]
Hello!!!
Sorry to bother you here but how did you revert BIOS from F14 for this motherboard?
As far as I know it can't be reverted...

**Comment by elieserme** [comment]
Hello! 
You can revert it using Q-Flash utility inside de BIOS (see attachment, pages 2-4). Downgrade will give you 15% more CPU performance, but will lost ReSize BAR support on Windows. If ReSize BAR is important to you, keep F14 BIOS and disable ReSize BAR for MacOS profile in BIOS.
att,
Elieser
[mb_manual_z370-features_BIOS.pdf](https://github.com/user-attachments/files/16334521/mb_manual_z370-features_BIOS.pdf)

**Comment by Aazamandius** [comment]
Got it!
Thanx!
